Rocky/Rocky/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAcess;
using Rocky_DataAcess.Repository.IRepository;
using Rocky_Models;
using Rocky_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _appRepo;
        public ApplicationTypeController(IApplicationTypeRepository appRepo)
        {
            _appRepo = appRepo;
        }
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList = _appRepo.GetAll();
            return View(objList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType obj)
        {

            if (ModelState.IsValid)
            {
                _appRepo.Add(obj);
                _appRepo.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET - EDIT
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id==0)
            {
                return NotFound();
            }
            //find method chỉ làm việc với primary key
            var obj = _appRepo.Find(Id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType obj)
        {
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (ModelState.IsValid)
            {
                _appRepo.Update(obj);
                _appRepo.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //find method chỉ làm việc với primary key
            var obj = _appRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST-DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _appRepo.Find(id.GetValueOrDefault());
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (obj == null)
            {
                return NotFound();
            }
            _appRepo.Remove(obj);
            _appRepo.Save();
            return RedirectToAction("Index");
        }
    }
}

Rocky/Rocky/Views/ApplicationType/Create.cshtml
@model Rocky_Models.ApplicationType

<form method="post" asp-action="Create" style="margin-top:80px!important;">
    <div class="border p-3 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="NameApp">Name App</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="NameApp" class="form-control" />

                        <span asp-validation-for="NameApp" class="text-danger"></span>
                    </div>

                </div>
               
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts    {
    @{
        <partial name="_ValidationScriptsPartial" />}
}

Rocky/Rocky/Views/ApplicationType/Delete.cshtml
@model Rocky_Models.ApplicationType


<form method="post" asp-action="DeletePost" style="margin-top:80px">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">

        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Delete Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="NameApp"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="NameApp" disabled class="form-control" />


                    </div>

                </div>
               
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-100" style="color:white!important;"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Rocky/Views/ApplicationType/Edit.cshtml
@model Rocky_Models.ApplicationType


<form method="post" style="margin-top:80px!important;">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">

        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="NameApp">Name App</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="NameApp" class="form-control" />

                        <span asp-validation-for="NameApp" class="text-danger"></span>
                    </div>

                </div>
                
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Rocky/Views/ApplicationType/Index.cshtml
@model IEnumerable<Rocky_Models.ApplicationType>


<div class="container p-3 bg-white" style="margin-top:80px!important;">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New Application Type
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                      Name
                    </th>
                    <th>
                        
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="50%">@obj.NameApp</td>
                        <td width="50%"></td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn mx-2">
                                    <i class="fas fa-edit" style="color:crimson!important;"></i>

                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn mx-2">
                                    <i class="fas fa-trash-alt"></i>

                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No application type exists.</p>
    }

</div>
