Rocky/Rocky/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAcess;
using Rocky_DataAcess.Repository.IRepository;
using Rocky_Models;
using Rocky_Models.ViewModel;
using Rocky_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class InquiryController : Controller
    {
        private readonly IInquiryHeaderRepository _inqHRepo;
        private readonly IInquiryDetailRepository _inqDRepo;
        
        [BindProperty]
        public InquiryVM InquiryVM { get; set; }
        public InquiryController(IInquiryDetailRepository inqDRepo, IInquiryHeaderRepository inqHRepo)
        {
            _inqDRepo = inqDRepo;
            _inqHRepo = inqHRepo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            InquiryVM = new InquiryVM()
            {
                InquiryHeader = _inqHRepo.FirstOrDefault(u => u.Id == id),
                InquiryDetail = _inqDRepo.GetAll(u=>u.InquiryHeaderId==id, includeProperties:"Product")
            };
            return View(InquiryVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            //load tất cả các mọi thứ trong inquiryDetail dựa vào ID của InquiryHeader 
            InquiryVM.InquiryDetail = _inqDRepo.GetAll(u => u.InquiryHeaderId == InquiryVM.InquiryHeader.Id);
            foreach (var detail in InquiryVM.InquiryDetail)
            {
                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    ProductId = detail.ProductId
                };
                shoppingCartList.Add(shoppingCart);

            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);
            //set session của riêng inquiry
            HttpContext.Session.Set(WC.SessionInquiryId, InquiryVM.InquiryHeader.Id);
            //chuyển hướng đến trang index bên trong cart controller
            return RedirectToAction("Index", "Cart");
        }

        [HttpPost]
       
        public IActionResult Delete()
        {
            //chọn Inquiry Header và Inquiry Detail cần xóa
            InquiryHeader inquiryHeader = _inqHRepo.FirstOrDefault(u => u.Id == InquiryVM.InquiryHeader.Id);
            IEnumerable<InquiryDetail> inquiryDetails = _inqDRepo.GetAll(u=>u.InquiryHeaderId == InquiryVM.InquiryHeader.Id);

            //  _inqDRepo.Remove();//hàm remove chỉ xóa 1 entity, chúng ta cần xóa 1 list nên ta phải thêm hàm DeleteRange
            _inqDRepo.RemoveRange(inquiryDetails);
            _inqHRepo.Remove(inquiryHeader);
            _inqHRepo.Save();

            return RedirectToAction(nameof(Index));
        }

        #region Call API
        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json ( new { data = _inqHRepo.GetAll()});
        }
        #endregion
    }
}

Rocky/Rocky/Views/Inquiry/Details.cshtml
@model Rocky_Models.ViewModel.InquiryVM

<form method="post">
    <input hidden asp-for="InquiryHeader.Id" />
    <br />
    <div class="backgroundWhite container">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0 row container">
                <div class="col-12 d-none d-md-block col-md-6 pb-1">
                    <i class="fas fa-shopping-cart"></i> &nbsp; Order Summary
                </div>
                <div class="col-12 col-md-4 offset-md-2 text-right">
                    <a asp-controller="InquiryController" asp-action="Index" class="btn btn-outline-info form-control btn-sm">Back to Inquiry</a>
                </div>
            </div>
            <div class="card-body pb-0">
                <div class="container rounded p-2">
                    <div class="row">
                        <div class="col-12 col-lg-6 pb-4">
                            <div class="row">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">PickUp Details:</span>
                                </h4>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Name</div>
                                <div class="col-9">
                                    <input asp-for="InquiryHeader.FullName" type="text" class="form-control" />
                                    <span asp-validation-for="InquiryHeader.FullName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Phone</div>
                                <div class="col-9">
                                    <input asp-for="InquiryHeader.PhoneNumber" type="text" class="form-control" />
                                    <span asp-validation-for="InquiryHeader.PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="row my-1">
                                <div class="col-3">Email</div>
                                <div class="col-9">
                                    <input asp-for="InquiryHeader.Email" type="text" class="form-control" />
                                    <span asp-validation-for="InquiryHeader.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row my-1">
                                <div class="col-3">Inquiry Date</div>
                                <div class="col-9">
                                    <input value="@Model.InquiryHeader.InquiryDate.ToShortDateString()" type="text" class="form-control" readonly />
                                </div>
                            </div>

                            <div class="row my-1 pt-2">
                                <div class="col-9 offset-3">
                                    <div class="row">
                                        <div class="col">
                                            <input type="submit" value="Convert To Cart" class="btn btn-info form-control" />
                                        </div>

                                        <div class="col">
                                            <input type="submit" value="Delete" class="btn btn-danger form-control"
                                                   formaction="/Inquiry/Delete" formmethod="post" />
                                            <!--Thay vì ghi như dưới có thể ghi như trên nếu trường hợp trong tag <input>-->
                                            <!--<a asp-controller="Inquiry" asp-action="Delete"-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-lg-5 offset-lg-1">
                            <h4 class="d-flex justify-content-between align-items-center mb-3">
                                <span class="text-info">Order Summary</span>
                            </h4>
                            <ul class="list-group mb-3">
                                @foreach (var prod in Model.InquiryDetail)
                                {
                                    <li class="list-group-item d-flex justify-content-between p-2">
                                        <div class="row container">
                                            <div class="col-8">

                                                <h6 class="my-0 text-info">@prod.Product.Name</h6>
                                                <small class="text-muted">Price : $@prod.Product.Price</small><br />
                                            </div>
                                            <div class="col-4">
                                            </div>
                                        </div>
                                    </li>
                                }
                            </ul>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Rocky/Rocky/Views/Inquiry/Index.cshtml

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />

<br />
<div class="border p-3 bg-white" style="margin-top:80px!important;">
    <div class="d-flex justify-content-between mb-3">
        <div class="p-2">
            <h2 class="text-info">Inquiry's List </h2>
        </div>

    </div>


    <table id="tblData" class="table table-striped table-bordered pt-2" style="width:100%">
        <thead class="" >
            <tr class="table-info">
                <th style="background:#ffe4e1; color:crimson;">Id</th>
                <th style="background:#ffe4e1!important; color:crimson!important;">Name</th>
                <th style="background:#ffe4e1!important; color:crimson!important;">Phone Number</th>
                <th style="background:#ffe4e1!important; color:crimson!important;">Email</th>
                <th style="background:#ffe4e1!important; color:crimson!important;"></th>
            </tr>
        </thead>
    </table>

</div>

@section Scripts{
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="~/js/inquiry.js"></script>
}