Rocky/Rocky/Controllers/CartController.cs
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAcess;
using Rocky_DataAcess.Repository.IRepository;
using Rocky_Models;
using Rocky_Models.ViewModel;
using Rocky_Utility;
using Rocky_Utility.BrainTree;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Rocky.Controllers
{   
    //cần quyền truy cập khi vào page cartshoping
    [Authorize]
    public class CartController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IApplicationUserRepository _userRepo;
        private readonly IProductRepository _prodRepo;
        private readonly IInquiryDetailRepository _inqDRepo;
        private readonly IInquiryHeaderRepository _inqHRepo;
        private readonly IOrderDetailRepository _orderDRepo;
        private readonly IOrderHeaderRepository _orderHRepo;
        private readonly ICouponRepository _couponRepo;
        private readonly IBrainTreeGate _brain;
        [BindProperty]
        public ProductUserVM ProductUserVM { get; set; }
        public CartController(ApplicationDbContext db, 
            IProductRepository prodRepo, IApplicationUserRepository userRepo, IInquiryDetailRepository inqDRepo, 
            IInquiryHeaderRepository inqHRepo, IOrderDetailRepository orderDRepo,
            IOrderHeaderRepository orderHRepo, IBrainTreeGate brain, ICouponRepository couponRepo)
        {
            _userRepo = userRepo;
            _prodRepo = prodRepo;
            _inqDRepo = inqDRepo;
            _inqHRepo = inqHRepo;
            _orderDRepo = orderDRepo;
            _orderHRepo = orderHRepo;
            _couponRepo = couponRepo;
            _brain = brain;
        }


        public IActionResult Index(double? total)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            //GET DATA FROM SESSION
            if(HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart)!=null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0 ) 
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }
            List<int> prodInCart = shoppingCartList.Select(i=>i.ProductId).ToList();


            IEnumerable<Product> prodListTemp = _prodRepo.GetAll(u => prodInCart.Contains(u.Id)); //lấy tất cả các id phù hợp với prodincart
            //IList<Product> prodList = new List<Product>();
            
            CartVM cartVM = new CartVM();

           
           
            foreach(var cartObj in shoppingCartList)
            {
                Product prodTemp = prodListTemp.FirstOrDefault(u => u.Id == cartObj.ProductId); //truy xuất từng product trong session
                prodTemp.TempSqFt = cartObj.SqFt;
              // prodList.Add(prodTemp);
                 cartVM.ProdList.Add(prodTemp);
               
            }

            List<string> couponCode = new List<string>();
            List<int> disCount = new List<int>();
            List<Coupon> couponTemp = _couponRepo.GetAll().ToList();
            foreach(var item in couponTemp)
            {
                couponCode.Add(item.CouponCode);
                disCount.Add(item.Discount);
            }

            ViewBag.CouponCode = couponCode;
            ViewBag.Discount = disCount;
                        
            return View(cartVM);           
        }
        
       

        //GET-POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        //public IActionResult IndexPost(List<Product> ProdList)
        //{
        public IActionResult IndexPost(CartVM CartVM)
        {
            List<ShoppingCart> shoppingCartLists = new List<ShoppingCart>();
            foreach (Product prod in CartVM.ProdList)
            {
                shoppingCartLists.Add(new ShoppingCart { ProductId = prod.Id, SqFt = prod.TempSqFt });
            }
            HttpContext.Session.Set(WC.SessionCart, shoppingCartLists);

            return RedirectToAction("Summary", new { total = CartVM.Total });
        }

        public IActionResult Summary(double total)
        {
            ApplicationUser applicationUser = new ApplicationUser();        
          
            //CREATE TOKEN
            var gateway = _brain.GetGateway();
            var clientToken = gateway.ClientToken.Generate(); 
            //token dữ liệu tạm thời nên dùng viewbag
            ViewBag.ClientToken = clientToken;//lưu trữ client token trong ViewBag               
          
            //tìm id của user để lấy dl
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            applicationUser = _userRepo.FirstOrDefault(u => u.Id == claim.Value);
           
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            //lấy dữ liệu từ session
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }
            List<int> prodInCart = shoppingCartList.Select(i => i.ProductId).ToList();
            //IEnumerable<Product> prodList = _db.Product.Where(u => prodInCart.Contains(u.Id));
            IEnumerable<Product> prodList = _prodRepo.GetAll(u => prodInCart.Contains(u.Id)); //chưa lấy đc sqft
            //lấy tất cả các dữ liệu truy xuất của iser đấy
            ProductUserVM = new ProductUserVM()
            {
                //ApplicationUser = _db.ApplicationUser.FirstOrDefault(u => u.Id == claim.Value),
                ApplicationUser = applicationUser,
                orderTotal = total
            };
            foreach(var cartObj in shoppingCartList)
            {
                Product prodTemp = _prodRepo.FirstOrDefault(u => u.Id == cartObj.ProductId);
                prodTemp.TempSqFt = cartObj.SqFt;
                ProductUserVM.ProductList.Add(prodTemp);
            }
                 
            return View(ProductUserVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection collection, ProductUserVM ProductUserVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                OrderHeader orderHeader = new OrderHeader()
                {
                    CreatedByUserId = claim.Value,
                    //FinalOrderTotal = ProductUserVM.ProductList.Sum(x=>x.Price*x.TempSqFt),
                    FinalOrderTotal = ProductUserVM.orderTotal,
                    City = ProductUserVM.ApplicationUser.City,
                    Address = ProductUserVM.ApplicationUser.Address,
                    OrderDate = DateTime.Now,
                    PhoneNumber = ProductUserVM.ApplicationUser.PhoneNumber,
                    Cmnd = ProductUserVM.ApplicationUser.Cmnd,
                    FullName = ProductUserVM.ApplicationUser.FullName,
                    Email = ProductUserVM.ApplicationUser.Email,
                    OrderStatus = WC.StatusPending
                };
                ////add order header vao database
                _orderHRepo.Add(orderHeader);
                _orderHRepo.Save();

                foreach (var prod in ProductUserVM.ProductList)
                {
                    OrderDetail orderDetail = new OrderDetail()
                    {
                        OrderHeaderId = orderHeader.Id,
                        PricePerSqFt = prod.Price,
                        Sqft = prod.TempSqFt,
                        ProductId = prod.Id
                    };
                    _orderDRepo.Add(orderDetail);
                }
                _orderDRepo.Save();

                string nonceFromTheClient = collection["payment_method_nonce"];
                var request = new TransactionRequest
                {
                    Amount = Convert.ToDecimal(orderHeader.FinalOrderTotal),
                    PaymentMethodNonce = nonceFromTheClient,
                    OrderId = orderHeader.Id.ToString(),
                    Options = new TransactionOptionsRequest
                    {
                        SubmitForSettlement = true //submit sau khi đã xác thực xong
                    }
                };

                var gateway = _brain.GetGateway();
                Result<Transaction> result = gateway.Transaction.Sale(request);
                if(result.Target.ProcessorResponseText=="Approved")
                {
                    orderHeader.TransactionId = result.Target.Id;
                    orderHeader.OrderStatus = WC.StatusApproved;
                }
                else
                {
                    orderHeader.OrderStatus = WC.StatusCancelled;
                }
                _orderHRepo.Save();

            //  return RedirectToAction(nameof(InquiryConfirmation), new { id = orderHeader.Id });
            return RedirectToAction("MyOrder", "Order");
        }
        
        
        public IActionResult InquiryConfirmation(int id=0)
        {
            OrderHeader orderHeader = _orderHRepo.FirstOrDefault(u => u.Id == id); //orderheader sẽ lấy dữ liệu từ orderheader_repo

            HttpContext.Session.Clear();

Rocky/Rocky/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAcess;
using Rocky_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rocky_Utility;
using Rocky_DataAcess.Repository.IRepository;

namespace Rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)] // ngăn quyền truy cập từ user
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _catRepo;
       
        public CategoryController(ICategoryRepository catRepo)
        {
            _catRepo = catRepo;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objList = _catRepo.GetAll();
            return View(objList);
        }

        //GET-CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (ModelState.IsValid)
            {
                _catRepo.Add(obj);
                _catRepo.Save();
                TempData[WC.Sucess] = "Category Added";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "Error while creating category!";
            return View(obj);
        }

        //GET - EDIT
        public IActionResult Edit(int? id)
        {   
            if(id==null || id == 0)
            {
                return NotFound();
            }
            //find method chỉ làm việc với primary key
            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (ModelState.IsValid)
            {
                _catRepo.Update(obj);
                _catRepo.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //find method chỉ làm việc với primary key
            var obj = _catRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST-DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _catRepo.Find(id.GetValueOrDefault());
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (obj == null)
            {
                return NotFound();
            }
            _catRepo.Remove(obj);
            _catRepo.Save();
                return RedirectToAction("Index");           
        }
    }
}

Rocky/Rocky/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAcess.Repository.IRepository;
using Rocky_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository _comRepo;
        public IEnumerable<Comment> CommentList { get; set; }
        public CommentController(ICommentRepository comRepo)
        {
            _comRepo = comRepo;
        }

        public IActionResult Index()
        {
            CommentList = _comRepo.GetAll(includeProperties: "CreatedBy,Product");
            return View(CommentList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            var obj = _comRepo.FirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _comRepo.Remove(obj);
            _comRepo.Save();
            return RedirectToAction("Index");
        }
    }
}

Rocky/Rocky/Controllers/CouponController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAcess.Repository.IRepository;
using Rocky_Models;
using Rocky_Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CouponController : Controller
    {
        private readonly ICouponRepository _couRepo;

        public CouponController(ICouponRepository couRepo)
        {
            _couRepo = couRepo;
        }

        public IActionResult Index()
        {
            IEnumerable<Coupon> objList = _couRepo.GetAll();
            return View(objList);
        }

        //GET-CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Coupon obj)
        {
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (ModelState.IsValid)
            {
                _couRepo.Add(obj);
                _couRepo.Save();
                TempData[WC.Sucess] = "Category Added";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "Error while creating category!";
            return View(obj);
        }

        //GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //find method chỉ làm việc với primary key
            var obj = _couRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST-EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Coupon obj)
        {
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (ModelState.IsValid)
            {
                _couRepo.Update(obj);
                _couRepo.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //find method chỉ làm việc với primary key
            var obj = _couRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST-DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _couRepo.Find(id.GetValueOrDefault());
            //kiểm tra điều kiện các rule trong model có giá trị true hay k?
            if (obj == null)
            {
                return NotFound();
            }
            _couRepo.Remove(obj);
            _couRepo.Save();
            return RedirectToAction("Index");
        }
    }
}

Rocky/Rocky/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http <!--từ view truy cập vào session-->
@inject IHttpContextAccessor HttpContextAccessor
    <!--thêm services từ dependency injection + get session-->
@using Rocky_Utility


    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Rocky</title>
        @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/login.css">
        <link rel="stylesheet" href="~/css/Header.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
        <link href="~/FontAwesome/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/Chatbox.css" />

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    </head>
    <body>

        <nav class="navbar navbar-expand-lg fixed-top App">
            <div class="container">
                <a href="/">
                    <a id="brand" class="navbar-brand" asp-controller="Home" asp-action="Index" style="width:130px !important;">
                        <img src="~/image/logo-Bakery-01.png" width="30" height="35" class="d-inline-block align-top js-scroll-trigger" alt="">
                        BAKERY
                    </a>
                </a>

                <div class="collapse navbar-collapse" id="navbarResposive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        @if (User.IsInRole(WC.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:crimson; text-decoration:none;">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Interaction">Interaction</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="RankOfProduct">Rank of product</a>

                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:crimson!important;">
                                    Ordered/Inquiry Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Comment" asp-action="Index">Legal content</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Coupon" asp-action="Index">Coupon</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
                                {
                                    <a asp-action="Index" asp-controller="Cart" class="nav-link js-scroll-trigger" id="navItem" style="color:crimson">
                                        @{
                                            var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count; //số lượng item trong session
                                        }
                                        <i class="fas fa-shopping-cart" style="color:crimson"></i> &nbsp; (@count)
                                    </a>

                                }
                                else
                                {
                                    <a href="#" class="nav-link js-scroll-trigger" style="color:crimson">
                                        <i class="fas fa-shopping-cart" style="color:crimson"></i> &nbsp; (0)
                                    </a>
                                }
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="/" style="text-decoration: none;">
                                    <a class="nav-link js-scroll-trigger" href="/" id="navItem">Product</a>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" id="navItem" asp-area="" asp-controller="Home" asp-action="Covid">Covid-19</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" id="navItem" asp-area="" asp-controller="Order" asp-action="MyOrder">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" href="#contact" id="navItem">Contact</a>
                            </li>

                            <li class="nav-item">
                                @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
                                {
                                    <a asp-action="Index" asp-controller="Cart" class="nav-link js-scroll-trigger" id="navItem" style="color:crimson">
                                        @{
                                            var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count; //số lượng item trong session
                                        }
                                        <i class="fas fa-shopping-cart" style="color:crimson"></i> &nbsp; (@count)
                                    </a>
                                    <!--hiển thị all-->

                                }
                                else
                                {
                                    <a class="nav-link js-scroll-trigger" style="color:crimson">
                                        <i class="fas fa-shopping-cart" style="color:crimson"></i> &nbsp; (0)
                                    </a>
                                }
                            </li>
                        }


                        <span style="margin: 0px 0px 0px 100px;"></span>
                        <br>

                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        @RenderBody()

        <partial name="_ChatBoxPartial"/>

        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="toastr.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
        <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="~/js/homController.js"></script>
        <script src="~/js/chart.min.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
        <ejs-scripts></ejs-scripts>
    </body>
</html>

Rocky/Rocky/Views/Shared/_Notifications.cshtml
@using Rocky_Utility

@if (TempData[WC.Sucess] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WC.Sucess]'); //thông báo đc lấy nội dung từ biến temp data
    </script>
}

@if (TempData[WC.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WC.Error]'); //thông báo đc lấy nội dung từ temp data
    </script>
}